name: deploy main branch 
env:
  VERCEL_ORG_ID: ${{ secrets.TEAM_ID }}
on:
  push:
    tags:
      - '*'

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get tags
        run: | 
          git fetch --tags
      - name: checkout tag
        run: |
          git checkout ${{ github.ref_name }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        env:
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        env:
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        env:
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}